// protoc --go_out=. --go-grpc_out=. cmd/proto/wallet.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: cmd/proto/wallet.proto

package wallet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Reference     string                 `protobuf:"bytes,3,opt,name=reference,proto3" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletRequest) Reset() {
	*x = WalletRequest{}
	mi := &file_cmd_proto_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletRequest) ProtoMessage() {}

func (x *WalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletRequest.ProtoReflect.Descriptor instead.
func (*WalletRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *WalletRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *WalletRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *WalletRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

type WalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *WalletData            `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletResponse) Reset() {
	*x = WalletResponse{}
	mi := &file_cmd_proto_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletResponse) ProtoMessage() {}

func (x *WalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletResponse.ProtoReflect.Descriptor instead.
func (*WalletResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *WalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WalletResponse) GetData() *WalletData {
	if x != nil {
		return x.Data
	}
	return nil
}

type WalletData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int64                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletData) Reset() {
	*x = WalletData{}
	mi := &file_cmd_proto_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletData) ProtoMessage() {}

func (x *WalletData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletData.ProtoReflect.Descriptor instead.
func (*WalletData) Descriptor() ([]byte, []int) {
	return file_cmd_proto_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *WalletData) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_cmd_proto_wallet_proto protoreflect.FileDescriptor

const file_cmd_proto_wallet_proto_rawDesc = "" +
	"\n" +
	"\x16cmd/proto/wallet.proto\x12\x06wallet\"]\n" +
	"\rWalletRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1c\n" +
	"\treference\x18\x03 \x01(\tR\treference\"R\n" +
	"\x0eWalletResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.wallet.WalletDataR\x04data\"&\n" +
	"\n" +
	"WalletData\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x03R\abalance2\x87\x01\n" +
	"\x06Wallet\x12>\n" +
	"\rCreditBalance\x12\x15.wallet.WalletRequest\x1a\x16.wallet.WalletResponse\x12=\n" +
	"\fDebitBalance\x12\x15.wallet.WalletRequest\x1a\x16.wallet.WalletResponseB\fZ\n" +
	"cmd/walletb\x06proto3"

var (
	file_cmd_proto_wallet_proto_rawDescOnce sync.Once
	file_cmd_proto_wallet_proto_rawDescData []byte
)

func file_cmd_proto_wallet_proto_rawDescGZIP() []byte {
	file_cmd_proto_wallet_proto_rawDescOnce.Do(func() {
		file_cmd_proto_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_proto_wallet_proto_rawDesc), len(file_cmd_proto_wallet_proto_rawDesc)))
	})
	return file_cmd_proto_wallet_proto_rawDescData
}

var file_cmd_proto_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_proto_wallet_proto_goTypes = []any{
	(*WalletRequest)(nil),  // 0: wallet.WalletRequest
	(*WalletResponse)(nil), // 1: wallet.WalletResponse
	(*WalletData)(nil),     // 2: wallet.WalletData
}
var file_cmd_proto_wallet_proto_depIdxs = []int32{
	2, // 0: wallet.WalletResponse.data:type_name -> wallet.WalletData
	0, // 1: wallet.Wallet.CreditBalance:input_type -> wallet.WalletRequest
	0, // 2: wallet.Wallet.DebitBalance:input_type -> wallet.WalletRequest
	1, // 3: wallet.Wallet.CreditBalance:output_type -> wallet.WalletResponse
	1, // 4: wallet.Wallet.DebitBalance:output_type -> wallet.WalletResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_proto_wallet_proto_init() }
func file_cmd_proto_wallet_proto_init() {
	if File_cmd_proto_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_proto_wallet_proto_rawDesc), len(file_cmd_proto_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_proto_wallet_proto_goTypes,
		DependencyIndexes: file_cmd_proto_wallet_proto_depIdxs,
		MessageInfos:      file_cmd_proto_wallet_proto_msgTypes,
	}.Build()
	File_cmd_proto_wallet_proto = out.File
	file_cmd_proto_wallet_proto_goTypes = nil
	file_cmd_proto_wallet_proto_depIdxs = nil
}
