// protoc --go_out=. --go-grpc_out=. cmd/proto/wallettransaction.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: cmd/proto/wallettransaction.proto

package walletTransaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WalletTransaction_CreditBalance_FullMethodName = "/walletTransaction.WalletTransaction/CreditBalance"
	WalletTransaction_DebitBalance_FullMethodName  = "/walletTransaction.WalletTransaction/DebitBalance"
)

// WalletTransactionClient is the client API for WalletTransaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalletTransactionClient interface {
	CreditBalance(ctx context.Context, in *WalletRequest, opts ...grpc.CallOption) (*WalletResponse, error)
	DebitBalance(ctx context.Context, in *WalletRequest, opts ...grpc.CallOption) (*WalletResponse, error)
}

type walletTransactionClient struct {
	cc grpc.ClientConnInterface
}

func NewWalletTransactionClient(cc grpc.ClientConnInterface) WalletTransactionClient {
	return &walletTransactionClient{cc}
}

func (c *walletTransactionClient) CreditBalance(ctx context.Context, in *WalletRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, WalletTransaction_CreditBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *walletTransactionClient) DebitBalance(ctx context.Context, in *WalletRequest, opts ...grpc.CallOption) (*WalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletResponse)
	err := c.cc.Invoke(ctx, WalletTransaction_DebitBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalletTransactionServer is the server API for WalletTransaction service.
// All implementations must embed UnimplementedWalletTransactionServer
// for forward compatibility.
type WalletTransactionServer interface {
	CreditBalance(context.Context, *WalletRequest) (*WalletResponse, error)
	DebitBalance(context.Context, *WalletRequest) (*WalletResponse, error)
	mustEmbedUnimplementedWalletTransactionServer()
}

// UnimplementedWalletTransactionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWalletTransactionServer struct{}

func (UnimplementedWalletTransactionServer) CreditBalance(context.Context, *WalletRequest) (*WalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreditBalance not implemented")
}
func (UnimplementedWalletTransactionServer) DebitBalance(context.Context, *WalletRequest) (*WalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DebitBalance not implemented")
}
func (UnimplementedWalletTransactionServer) mustEmbedUnimplementedWalletTransactionServer() {}
func (UnimplementedWalletTransactionServer) testEmbeddedByValue()                           {}

// UnsafeWalletTransactionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalletTransactionServer will
// result in compilation errors.
type UnsafeWalletTransactionServer interface {
	mustEmbedUnimplementedWalletTransactionServer()
}

func RegisterWalletTransactionServer(s grpc.ServiceRegistrar, srv WalletTransactionServer) {
	// If the following call panics, it indicates UnimplementedWalletTransactionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WalletTransaction_ServiceDesc, srv)
}

func _WalletTransaction_CreditBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletTransactionServer).CreditBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletTransaction_CreditBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletTransactionServer).CreditBalance(ctx, req.(*WalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WalletTransaction_DebitBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalletTransactionServer).DebitBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WalletTransaction_DebitBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalletTransactionServer).DebitBalance(ctx, req.(*WalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalletTransaction_ServiceDesc is the grpc.ServiceDesc for WalletTransaction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalletTransaction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "walletTransaction.WalletTransaction",
	HandlerType: (*WalletTransactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreditBalance",
			Handler:    _WalletTransaction_CreditBalance_Handler,
		},
		{
			MethodName: "DebitBalance",
			Handler:    _WalletTransaction_DebitBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cmd/proto/wallettransaction.proto",
}
