// protoc --go_out=. --go-grpc_out=. cmd/proto/transaction.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: cmd/proto/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_cmd_proto_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_cmd_proto_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TransactionData       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_cmd_proto_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_cmd_proto_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionResponse) GetData() *TransactionData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TransactionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Reference     string                 `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionData) Reset() {
	*x = TransactionData{}
	mi := &file_cmd_proto_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionData) ProtoMessage() {}

func (x *TransactionData) ProtoReflect() protoreflect.Message {
	mi := &file_cmd_proto_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionData.ProtoReflect.Descriptor instead.
func (*TransactionData) Descriptor() ([]byte, []int) {
	return file_cmd_proto_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TransactionData) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *TransactionData) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_cmd_proto_transaction_proto protoreflect.FileDescriptor

const file_cmd_proto_transaction_proto_rawDesc = "" +
	"\n" +
	"\x1bcmd/proto/transaction.proto\x12\vtransaction\"{\n" +
	"\x12TransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"a\n" +
	"\x13TransactionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x120\n" +
	"\x04data\x18\x02 \x01(\v2\x1c.transaction.TransactionDataR\x04data\"[\n" +
	"\x0fTransactionData\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\treference\x18\x02 \x01(\tR\treference\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type2e\n" +
	"\vTransaction\x12V\n" +
	"\x11CreateTransaction\x12\x1f.transaction.TransactionRequest\x1a .transaction.TransactionResponseB\x11Z\x0fcmd/transactionb\x06proto3"

var (
	file_cmd_proto_transaction_proto_rawDescOnce sync.Once
	file_cmd_proto_transaction_proto_rawDescData []byte
)

func file_cmd_proto_transaction_proto_rawDescGZIP() []byte {
	file_cmd_proto_transaction_proto_rawDescOnce.Do(func() {
		file_cmd_proto_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cmd_proto_transaction_proto_rawDesc), len(file_cmd_proto_transaction_proto_rawDesc)))
	})
	return file_cmd_proto_transaction_proto_rawDescData
}

var file_cmd_proto_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cmd_proto_transaction_proto_goTypes = []any{
	(*TransactionRequest)(nil),  // 0: transaction.TransactionRequest
	(*TransactionResponse)(nil), // 1: transaction.TransactionResponse
	(*TransactionData)(nil),     // 2: transaction.TransactionData
}
var file_cmd_proto_transaction_proto_depIdxs = []int32{
	2, // 0: transaction.TransactionResponse.data:type_name -> transaction.TransactionData
	0, // 1: transaction.Transaction.CreateTransaction:input_type -> transaction.TransactionRequest
	1, // 2: transaction.Transaction.CreateTransaction:output_type -> transaction.TransactionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cmd_proto_transaction_proto_init() }
func file_cmd_proto_transaction_proto_init() {
	if File_cmd_proto_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cmd_proto_transaction_proto_rawDesc), len(file_cmd_proto_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cmd_proto_transaction_proto_goTypes,
		DependencyIndexes: file_cmd_proto_transaction_proto_depIdxs,
		MessageInfos:      file_cmd_proto_transaction_proto_msgTypes,
	}.Build()
	File_cmd_proto_transaction_proto = out.File
	file_cmd_proto_transaction_proto_goTypes = nil
	file_cmd_proto_transaction_proto_depIdxs = nil
}
